version: '3'

services:
  app:
    build: ./docker
    environment:
      DISABLE_DEFAULT_SERVER: 1
      VERTICA_HOST: vertica
      VERTICA_PORT: 5433
      VERTICA_USER: dbadmin
      VERTICA_PASS: password
      VERTICA_DB: docker
    command: tail -f /dev/null
    links:
      - vertica
    volumes:
      - ./:/var/www
  vertica:
    # @see https://hub.docker.com/r/jbfavre/vertica
    # @see https://github.com/jbfavre/docker-vertica
    image: jbfavre/vertica:9.x
    environment:
      DATABASE_PASSWORD: "password"
      DATABASE_NAME: "docker"
